### PR TITLE
update version to 2.7.5

### PR DESCRIPTION
**Pull request by ifurther**

### CODE REVIEW

**Comment by wvandelli** [comment]
Hello @ifurther,

  thanks for much for the pull request. I am quite busy this week, I hope I will be able to look into it next week. Few quick questions in the meanwhile:

- I suppose autofs works for you on arch with the included changes, right? I use systemd to mount cvmfs, so I never tried with autofs
- In case, could you check if the instructions in [the postinstall message](https://github.com/wvandelli/cvmfs-aur/blob/master/cvmfs.install#L14) are correct?
- I am not sure a gitignore file is welcome in the AUR repo, I have a vague recollection .. to be checked!

Thanks. Cheers
                       Wainer

**Comment by ifurther** [comment]
Sorry I am busy too. I checked the postinstall message and I add some message for autofs mod. I see the gitignore file in some aur repo , so I think it is optional file.

**Comment by wvandelli** [comment]
Thanks a lot @ifurther.

@fsiegert, what do you think, should we merge this?

Cheers
        Wainer

**Comment by fsiegert** [comment]
Sounds good to me, thanks!

**Comment by wvandelli** [comment]
Manually merged with minor changes.

**Pull request closed without merging**
